# Euler_0003
# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143 ?

function euler_0003(n)
    # Assume n is greater than 2.
    # Eliminate all factors of 2 to speed up the main loop.
    i = 2
    while n % i == 0
        n = n / i
    end
    if n == 1
        return i
    end
    i = 3
    while n > 1 
        if n % i == 0
            n = n / i
        else
            i += 2
        end
    end
    return i
end


# Euler_0002
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

function euler_0002(n)
    sum = 0
    a, b = 1, 2
    while a < n
        if a % 2 == 0
            sum += a
        end
        # println("sum: $sum, a: $a, b: $b")
        a, b = b, a + b
    end
    return sum
end


# Euler_0001
# If we list all the natural numbers below  that are multiples of  or , we get  and . The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.

function euler_0001(n)
    sum = 0
    for i in 1:n-1
        if i % 3 == 0 || i % 5 == 0
            sum += i
        end
    end
    return sum
end