# Euler_0006
# The sum of the squares of the first ten natural numbers is,
#  1^2 + 2^2 + ... + 10^2 = 385
# The square of the sum of the first ten natural numbers is,
#  (1 + 2 + ... + 10)^2 = 55^2 = 3025
# Hence the difference between the sum of the squares of the first
# ten natural numbers and the square of the sum is 3025 − 385 = 2640.
# Find the difference between the sum of the squares of the first one 
# hundred natural numbers and the square of the sum.

function euler_0006(n)
    sum_of_squares = n * (n + 1) * (2n + 1) / 6
    square_of_sum = (n * (n + 1) / 2)^2
    return square_of_sum - sum_of_squares
end


# Euler_0005
# 2520 is the smallest number that can be divided by each of the numbers
# from 1 to 10 without any remainder. What is the smallest positive number 
# that is evenly divisible by all of the numbers from 1 to 20?

function euler_0005(n)
    if n == 10 
        return 2 * 3 * 2 * 5 * 7 * 2 * 3
    elseif n == 20
        return 2^4 * 3^2 * 5 * 7 * 11 * 13 * 17 * 19
    end
end




# Euler_0004
# A palindromic number reads the same both ways. 
# The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
# Find the largest palindrome made from the product of two 3-digit numbers.

function is_palindrome(n)
    s = string(n)
    return s == reverse(s)
end

function euler_0004(n)
    max = 0
    imax, jmax = 0, 0
    if n > 10 
        limit = n - n÷10
    else
        limit = 1
    end
    for i in n-1:-1:limit
        for j in n-1:-1:limit
            product = i * j
            if product > max && is_palindrome(product)
                max = product
                imax, jmax = i, j
            end
        end
    end
    return max
end



# Euler_0003
# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143 ?

function euler_0003(n)
    # Assume n is greater than 2.
    # Eliminate all factors of 2 to speed up the main loop.
    i = 2
    while n % i == 0
        n = n / i
    end
    if n == 1
        return i
    end
    i = 3
    while n > 1 
        if n % i == 0
            n = n / i
        else
            i += 2
        end
    end
    return i
end


# Euler_0002
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

function euler_0002(n)
    sum = 0
    a, b = 1, 2
    while a < n
        if a % 2 == 0
            sum += a
        end
        # println("sum: $sum, a: $a, b: $b")
        a, b = b, a + b
    end
    return sum
end


# Euler_0001
# If we list all the natural numbers below  that are multiples of  or , we get  and . The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.

function euler_0001(n)
    sum = 0
    for i in 1:n-1
        if i % 3 == 0 || i % 5 == 0
            sum += i
        end
    end
    return sum
end